controller_list:
  - name: fake_front_left_leg_controller
    joints:
      - joint_left_front_1
      - joint_left_front_2
      - joint_left_front_3
      - joint_left_front_4
  - name: fake_end_left_front_leg_controller
    joints:
      - joint_left_front_4
initial:  # Define initial robot poses.
  - group: front_left_leg
    pose: Left_front_leftPose1