front_left_leg:
  kinematics_solver: srv_kinematics_plugin/SrvKinematicsPlugin
  kinematics_solver_search_resolution: 0.010
  kinematics_solver_timeout: 0.050
end_left_front_leg:
  kinematics_solver: srv_kinematics_plugin/SrvKinematicsPlugin
  kinematics_solver_search_resolution: 0.010
  kinematics_solver_timeout: 0.050
